import { Metadata } from "next"
import { fetchContentByUUID, fetchStreamContent } from "../../lib"
import { ContentByUUIDResponse } from "../../lib/lib.types"

export const metadata: Metadata = {
  title: "Landing",
  description: "Generated by create next app",
}

export default async function Home() {
  const streamContentResponse = await fetchStreamContent()

  const data = await Promise.all<ContentByUUIDResponse>(
    streamContentResponse.results.map(async (str) => {
      return await fetchContentByUUID(str)
    })
  )
  return (
    <>
      <p>Here&apos;s some stories and junk</p>
      {data.map((story) => {
        const storyPublishedDate = new Date(story.first_published)
        const storyLink = `/${storyPublishedDate.getFullYear()}/${
          storyPublishedDate.getMonth() + 1
        }/${storyPublishedDate.getDate()}/${story.id}`
        return (
          <div key={story.id}>
            {"{"}
            <div className="px-4 flex flex-col">
              <span>Title: {story.headline}</span>
              <span>Description: {story.og_description}</span>
              <pre>
                Link:{" "}
                <a
                  className="text-blue-600 hover:underline cursor-pointer"
                  href={storyLink}
                >
                  {JSON.stringify(storyLink)}
                </a>
              </pre>
            </div>
            {"}"}
          </div>
        )
      })}
    </>
  )
}
